<Project Sdk="Microsoft.NET.Sdk">

  <!-- Pruebas unitarias: validan el dominio y los handlers sin I/O. -->

  <PropertyGroup>
    <RootNamespace>PokemonApi.UnitTests</RootNamespace>
    <AssemblyName>PokemonApi.UnitTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PokemonApi.Domain\PokemonApi.Domain.csproj" />
    <ProjectReference Include="..\..\src\PokemonApi.Application\PokemonApi.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
