<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Pruebas de integracion: levantan la API completa en memoria con
    WebApplicationFactory y verifican los endpoints de punta a punta.
  -->

  <PropertyGroup>
    <RootNamespace>PokemonApi.IntegrationTests</RootNamespace>
    <AssemblyName>PokemonApi.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PokemonApi.Api\PokemonApi.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
